### ISSUE TITLE
Bug on click back

### ISSUE THREAD

**Issue by shish-ko** [ArturZabashta/rs-clone#10]
### Page name lefts on its place when clicking navigate back.
![Снимок экрана от 2023-02-09 15-55-08](https://user-images.githubusercontent.com/107854857/217818752-47762c5c-584c-457f-8fd2-8116e079360d.png)
![Снимок экрана от 2023-02-09 15-55-19](https://user-images.githubusercontent.com/107854857/217818788-4c3ade1f-2e4e-4efb-bdbd-b2ba453594c0.png)

**Comment by ArturZabashta** [comment]
Fix this bugg
